# Default endpoint URLs for the ORCID OAuth API

production:
  site: http://joss.theoj.org
  authorize_url: http://orcid.org/oauth/authorize?show_login=true
  token_url: http://pub.orcid.org/oauth/token
  client_id: <%= ENV["ORCID_KEY"] %>
  client_secret: <%= ENV["ORCID_SECRET"] %>

development:
  site: http://localhost:3000
  authorize_url: http://orcid.org/oauth/authorize#show_login
  token_url: http://pub.orcid.org/oauth/token
  client_id: APP-GNG60TQ72FJQLPUV
  client_secret: 3cf2ff51-7861-43e1-9313-f5db4fbaa279

test:
  site: http://0.0.0.0:3000
  authorize_url: https://orcid.org/oauth/authorize#show_login
  token_url: https://pub.orcid.org/oauth/token
  client_id:
  client_secret:
